### ISSUE TITLE
Recent errors

### ISSUE THREAD

**Issue by mquevill** [pren/poltype#15]
It appears that some recent changes may have introduced some errors in these scripts. I have been trying to run the Ammonia example in `Examples/SymmetryAmmonia` via
```shell
cd Examples/SymmetryAmmonia/
rm -r !(ammonia.sdf|poltype.ini) # remove everything except these files
python ../../PoltypeModules/poltype.py
```

With `dontfrag=False`, I get the following error:
```python
Traceback (most recent call last):
  File "~/git/poltype/PoltypeModules/poltype.py", line 1078, in <module>
    params=poltype.main()
  File "~/git/poltype/PoltypeModules/poltype.py", line 846, in main
    params= self.GenerateParameters()
  File "~/git/poltype/PoltypeModules/poltype.py", line 1024, in GenerateParameters
    rotbndindextoparentindextofragindex,rotbndindextofragment,rotbndindextofragmentfilepath,equivalentfragmentsarray,equivalentrotbndindexarrays=frag.GenerateFragments(self,self.mol,torlist,WBOmatrix) # returns list of bond indexes that need parent molecule to do torsion scan for (fragment generated was same as the parent0
  File "~/git/poltype/PoltypeModules/fragmenter.py", line 794, in GenerateFragments
    equivalentrotbndindexes=GrabEquivalentRotBndIndexes(poltype,equivalentrotbndindexarrays,rotbndindex)
UnboundLocalError: local variable 'rotbndindex' referenced before assignment
```

With `dontfrag=True`, I get the following error:
```python
Traceback (most recent call last):
  File "~/git/PoltypeModules/poltype.py", line 1078, in <module>
    params=poltype.main()
  File "~/git/PoltypeModules/poltype.py", line 846, in main
    params= self.GenerateParameters()
  File "~/git/PoltypeModules/poltype.py", line 1045, in GenerateParameters
    torfit.process_rot_bond_tors(self,optmol)
  File "~/git/poltype/PoltypeModules/torsionfit.py", line 1036, in process_rot_bond_tors
    mol,cls_mm_engy_dict,cls_qm_engy_dict,cls_angle_dict)
TypeError: cannot unpack non-iterable NoneType object
```
All `cls_mm_engy_dict`, `cls_qm_engy_dict`, and `cls_angle_dict` are `{}`.

Please let me know if there are additional files or information you might need.

**Comment by walkerbdev** [comment]
Hey,

Please dont use the fragmenter right now, the bugs are still working out and I have not pushed latest versions nor tested on enough molecules. If you look at latest poltype on github default is dontfrag=True.

**Comment by walkerbdev** [comment]
Okay something looks like is going wrong with torsion fitting. Can you please send me a onedrive link with all the files you used to run?

**Comment by walkerbdev** [comment]
Oh you are using an example we already have, I will take a look

**Comment by mquevill** [comment]
Yeah, I just wanted to try both options, but it even breaks without using the fragmenter. I wanted a very simple test case, so I chose the included Ammonia example.

**Comment by mquevill** [comment]
There shouldn't be any torsions to calculate in NH3, though, right?

**Comment by walkerbdev** [comment]
Okay the issue is more or less entering the torsionfitting function without torsions to fit. New version is fixed.

**Comment by mquevill** [comment]
It looks like an indentation issue that was introduced in eb0b94cface6d600d71d0a34c7abd111ead3055b. The return statement of `fit_rot_bond_tors()` was inside the `for tor in poltype.torlist:` loop. Unindenting it by one should allow for proper returning. (Oh the joys of whitespace-dependent languages!)
https://github.com/pren/poltype/blob/1370038622322622fedd4b68f13e6e425c59f5e9/PoltypeModules/torsionfit.py#L805

**Comment by walkerbdev** [comment]
oh geeze, thanks for catching that haha. I dont even remember touching that
line. I must have yanked and also indented same time.
