### ISSUE TITLE
How to enter the parameters into prm file?

### ISSUE THREAD

**Issue by hesam-a** [pren/poltype#37]
Dear all,

I got the parameters of the chopped fragments of a molecule and now that I want to integrate them all and enter to the prm file with new numbers, I can't use them and tinker can't read them, for example when I try to run pdbxyz it can't read them, any suggestion?

Hesam

**Comment by walkerbdev** [comment]
It will be easier for you to just not add parameters in final key to prm file, just reference the prm file in your key file with a "parameters" line and then when using tinker, use a -k flag to specify the key file, which references your parameter file.

**Comment by hesam-a** [comment]
I guess I didn't ask my question well, when I do pdbxyz it does convert to xyz but it puts 0 for all atom types and when I want to soak for example acetamide into a waterbox I get something like this      1  C           NaN         NaN         NaN     0     2     5     6     7     2  C           NaN         NaN         NaN     0     1     3     4     3  N           NaN         NaN         NaN     0     2     8     9     4  O           NaN         NaN         NaN     0     2     5  H           NaN         NaN         NaN     0     1     6  H           NaN         NaN         NaN     0     1     7  H           NaN         NaN         NaN     0     1     8  H           NaN         NaN         NaN     0     3     9  H           NaN         NaN         NaN     0     3
    On Tuesday, July 28, 2020, 10:42:36 AM EDT, Brandon Walker <notifications@github.com> wrote:  
 
 


It will be easier for you to just not add parameters in final key to prm file, just reference the prm file in your key file with a "parameters" line and then when using tinker, use a -k flag to specify the key file, which references your parameter file.

**Comment by hesam-a** [comment]
should I enter the atom types into the xyz file manually?
    On Tuesday, July 28, 2020, 12:11:57 PM EDT, Hesam Arabzadeh <hessam_arabzadeh@ymail.com> wrote:  
 
  I guess I didn't ask my question well, when I do pdbxyz it does convert to xyz but it puts 0 for all atom types and when I want to soak for example acetamide into a waterbox I get something like this      1  C           NaN         NaN         NaN     0     2     5     6     7     2  C           NaN         NaN         NaN     0     1     3     4     3  N           NaN         NaN         NaN     0     2     8     9     4  O           NaN         NaN         NaN     0     2     5  H           NaN         NaN         NaN     0     1     6  H           NaN         NaN         NaN     0     1     7  H           NaN         NaN         NaN     0     1     8  H           NaN         NaN         NaN     0     3     9  H           NaN         NaN         NaN     0     3
    On Tuesday, July 28, 2020, 10:42:36 AM EDT, Brandon Walker <notifications@github.com> wrote:  
 
 


It will be easier for you to just not add parameters in final key to prm file, just reference the prm file in your key file with a "parameters" line and then when using tinker, use a -k flag to specify the key file, which references your parameter file.

**Comment by walkerbdev** [comment]
Yes, you can enter the atom types manually, or "correct" the atom types in
PDB fields. The program is reading pdb file from a database and must not be
recognizing some of the fields in your PDB file.
