### ISSUE TITLE
poltype not able to deal with Z-only multipole frame

### ISSUE THREAD

**Issue by leucinw** [pren/poltype#38]
Poltype fails to handle **Z-only** multipole frame. Error message is here

 
> 1 Traceback (most recent call last):
  2   File "/home/liuchw/poltype-latest/PoltypeModules/poltype.py", line 1109, in <module>
  3     params=poltype.main()
  4   File "/home/liuchw/poltype-latest/PoltypeModules/poltype.py", line 878, in main
  5     params= self.GenerateParameters()
  6   File "/home/liuchw/poltype-latest/PoltypeModules/poltype.py", line 967, in GenerateParameters
  7     lfzerox,atomindextoremovedipquad,atomtypetospecialtrace,atomindextoremovedipquadcross = mpole.gen_peditinfile(self,mol)
  8   File "/home/liuchw/poltype-latest/PoltypeModules/multipole.py", line 253, in gen_peditinfile
  9     poltype.localframe2[atomidx - 1]=sorteduniquetypeneighbsnorepeat[1]
 10 IndexError: list index out of range

**Comment by pren** [comment]
What molecule is this? Which atom? Please share files /path to files.

Is POLEDIT used to create the frame? Is this error after POLEDIT call?

Brandon tested Z-only on few molecules before?

**Comment by leucinw** [comment]
The molecule is Methylamine. I tried to use Z-only for N and C atoms. These are user-specified frames (not written by poltype/poledit). This should be the error before poledit call, because the .key is not generated.
