### ISSUE TITLE
Nitrogen is not being added to an adjacent aromatic ring.

### ISSUE THREAD

**Issue by anessler** [pren/poltype#39]
While parameterizing the structure XAFPAY from the CCDC, I noticed that the experimental structures show the bonds from the nitrogen atom parallel to the bonds of an adjacent aromatic ring. Minimizing the structure with parameters from poltype2 these bonds adjust slightly so they are no longer parallel suggesting that the nitrogen is no longer included in the conjugated system. The attached PNG is an attempt to show an experimental crystal structure overlaid with a minimized parameter structure to juxtapose the nitrogen/ring bonds.
![CP23_aroma](https://user-images.githubusercontent.com/33242946/89213211-5cf53b80-d58a-11ea-92ff-482176b9097a.png)

**Comment by pren** [comment]
Please check the QM (opt) structure first. POLTYPE may be using the QM structure. If you would like to keep it flat (sp2 like), you can add oop term to the H and C that connects to the N. You can borrow the formamide N OOP parameters in amoeba09.prm.

**Comment by anessler** [comment]
Thank you very much for the fix. I had originally tried using a pitor parameter between the nitrogen and the aromatic ring. This also seemed to hold the nitrogen bonds in the same plane as the aromatic ring. Is there a reason to prefer using the OOP parameter over pitor?

**Comment by pren** [comment]
Pitor does not prevent out-of-plane bending of NH2. It actually does the opposite.
