### ISSUE TITLE
"Error: Invalid gaussian directory" when use_gausoptonly is flagged as true

### ISSUE THREAD

**Issue by jpetersen48** [pren/poltype#50]
Hello,

I recently attempted to use POLTYPE2 on the zwitterion of proline. When I submitted the job with the suggested flags for zwitterions: 

> optpcm=True
> toroptpcm=True
> torsppcm=True
> use_gausoptonly=True

I was given the error:

> ERROR: Invalid Gaussian directory:

After testing the individual flags, I found that this error was only returned when use_gausoptonly=True was active. If it is relevant, the error that ends the job when that flag is inactive appears to be this, within the "-opt.log" file

> PsiException: Could not converge geometry optimization in 5 iterations.

**Comment by walkerbdev** [comment]
Hello,

Would it be possible to see a link of files (in some box link etc), for
troubleshooting?

Thanks

**Comment by walkerbdev** [comment]
Also, could you check to see if your gaussian executable works (test on
anything)? Then also open any .com file and locate the referenced folder
location, then check to see if this folder exists in your file system? If
it does not, there should be a place in poltype.log file where it says,
mkdir /folder.. etc .

**Comment by jpetersen48** [comment]
Hello,

Here's a link to the entire directory that I was using poltype within.

https://notredame.box.com/s/avwnsdn6rbxyqrku0yccig66pi6fldf7

I have also tested gaussian again, I am able to perform calculations with gaussian. Please let me know if there is anything else I can do to assist.

**Comment by walkerbdev** [comment]
Hey,

I have attached a screen shot of what I see when I attempt to access the
link. I have logged in via my institution instead of University of Notre
Dame.

Also, in the poltype job folder, there should be a *opt.com file. In that
file there should be a folder location on the top of the file. I just want
to make sure that this folder location exists on your cluster.

- Brandon

**Comment by walkerbdev** [comment]
It would seem I cannot attach a screenshot from email response. Basically it says the shared link or file is unavailable to you.

**Comment by walkerbdev** [comment]
Also, please attach your source for your envioronment

**Comment by jpetersen48** [comment]
Oh, sorry, I forgot to change permissions. Here's a new link with my .bashrc profile included. Let me know if you need anything else, or if this doesn't work again.

https://notredame.box.com/s/qime8z0e28ks1n38d68d6314o5tmfqgm

**Comment by walkerbdev** [comment]
Okay so a couple of suggestions. 
1) Just keep the poltype code directory seperate from things like GMDA or your poltype jobs. So like you can keep a seperate folder somewhere else "PoltypeJobs", then within this folder you can submit jobs according to the documentation.

2) What is basically happening is that you are telling poltype you want to use gaussian, but I dont see it in your.bashrc so it doesnt know where to find it. There is example bashrc on readme.install on the gh-pages branch. Try making a new bashrc like the example and then try again.

**Comment by jpetersen48** [comment]
For point 1, that makes sense. Point 2, I think I address that in the submission script pol.sh, but let me know if I'm incorrect:

```
module load tinker/8.8.1/intel/19.0
module load gaussian
module load python/3.7.3
module load conda

export PATH='/afs/crc.nd.edu/x86_64_linux/c/conda/miniconda2/4.5.4/bin:$PATH'
source activate poltype
export g09root=/afs/crc.nd.edu/x86_64_linux/g/gaussian/09/pgi/16.3/build_RH7/g09
export GAUSS_SCRDIR=/scratch365/jpeter20/poltype/
export GDMADIR=/afs/crc.nd.edu/group/corcelli/Poltype/gdma/bin/
export PATH=/scratch365/jpeter20/poltype/gdma/bin/:$PATH
export PSI_SCRATCH=/scratch365/jpeter20/poltype/
export PATH=/afs/crc.nd.edu/x86_64_linux/t/tinker/8.8.1/tinker/source/:$PATH

nohup python PoltypeModules/poltype.py

```

**Comment by walkerbdev** [comment]
Oppps I didnt look inside your .sh. Hmmm here is one point of difference
between our sources.
source $g09root/g09/bsd/g09.profile
Maybe try doing a "which g09"? Also could you copy that error and search
for it via grep in PoltypeModules/poltype.py , there should be a reference
to a self.gausdir and self.gausexe, write before the error
statement (below), can you print these variables to see what poltype thinks
they are?
 if self.which(os.path.join(self.gausdir, self.gausexe)) is None:
                print("ERROR: Invalid Gaussian directory: ", self.gausdir)



 $g09root/g09/bsd/g09.profile (just showing top where it seems to be
setting env for gaussian on our cluster)
i#
# These commands set up for use of Gaussian 09.  They should be source'd
# into each Gaussian 09 user's .login file, after setting the following
# environment variable:
#
# g09root -- Directory which contains the g09 main directory.  Defaults
#            to users's home directory if not defined before entry.
#
# Top directories for the program:
#
gr=$HOME
if [ "$g09root" ]
  then gr=$g09root
  fi
export GAUSS_EXEDIR="$gr/g09/bsd:$gr/g09/local:$gr/g09/extras:$gr/g09"
export GAUSS_LEXEDIR="$gr/g09/linda-exe"
export GAUSS_ARCHDIR="$gr/g09/arch"
export GV_DIR="$gr/gv"
if [ -e "$GV_DIR/gview.app" ]; then
  alias gv='open $GV_DIR/gview.app'
else
  alias gv="$GV_DIR/gview.csh"
  fi
if [ "$PATH" ]; then
  export PATH="$PATH:$GAUSS_EXEDIR"
else
  export PATH="$GAUSS_EXEDIR"
  fi
export _DSM_BARRIER="SHM"
if [ "$LD_LIBRARY64_PATH" ]; then
  export LD_LIBRARY64_PATH="$GAUSS_EXEDIR:$GV_DIR/lib:$LD_LIBRARY64_PATH"
else

**Comment by walkerbdev** [comment]
I also see this in your output log. Is the source activate poltype supposed
to be like "conda activate poltype"? Like is poltype the name of your conda
env?

/opt/crc/c/conda/miniconda2/4.5.4/etc/profile.d/conda.sh: line 15: dirname:
command not found
/opt/crc/c/conda/miniconda2/4.5.4/etc/profile.d/conda.sh: line 16: dirname:
command not found

**Comment by mquevill** [comment]
[The following is specific to Notre Dame's CRC computing cluster.]

The default version of Gaussian is 16B01 (on the CRC), which uses the executable `g16` instead of `g09`. [If you want to keep using g09, run `module load gaussian/09E01`, but it is deprecated on the CRC.]

Poltype should be able to find Gaussian for you once the module is loaded, so you shouldn't need to set the `g16root`.
