### ISSUE TITLE
value error

### ISSUE THREAD

**Issue by ahmedo047** [pren/poltype#58]
Hi,

POLTYPE gives the "ValueError" while running it to get the AMOEBA parameters of anthracene. Do you know how I can fix this error?
I attached a folder with all files.
[anthracene.zip](https://github.com/pren/poltype/files/5469029/anthracene.zip)

**Comment by walkerbdev** [comment]
Looks like some sort of issue with Psi4 installation, I have ran the molecule and everything seems to be fine. Try reinstalling psi4.
