### ISSUE TITLE
Incorrect polarization groups for ions

### ISSUE THREAD

**Issue by mquevill** [pren/poltype#70]
While running poltype with an ionic species (this issue seems to be with ions more than neutrally-charged molecules), I got a few errors within the `potential` call (`potential 6 propylammonium.xyz_2 -k propylammonium.key_2 propylammonium.pot N 0.1`):
```
POLARGRP  --  Check Polarization Groups for Atoms      XXX and      YYY
```
However, poltype keeps trying to continue, despite `potential` finishing with an error. Since the .key_3 file is not properly output, the following command raises and error:
```
sed -e '/\(.* none$\|^#\|^fix\|^potential-offset\)/d' propylammonium.key_3 > propylammonium.key_3_tmp
```

I'm not sure exactly where this issue is coming from, however. With the current `poltype2` branch, it seems to happen with ionic species, but I haven't run into this issue with neutral species.

### Input Files

propylammonium.sdf:
```
 OpenBabel12102010403D

 14 13  0  0  0  0  0  0  0  0999 V2000
    1.0064   -0.0613    0.0777 N   0  3  0  0  0  0  0  0  0  0  0  0
    0.6335    0.1113   -0.8654 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.6328   -0.9641    0.3999 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.6239    0.6664    0.6959 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.4890   -0.0470    0.0907 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.0057   -1.1367   -0.8352 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.5254   -1.1647   -0.8571 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.7989   -0.2085    1.1274 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.7997    0.9499   -0.2355 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.6346   -0.9729   -1.8539 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.6329   -2.1154   -0.5103 H   0  0  0  0  0  0  0  0  0  0  0  0
    4.9302   -0.2108   -1.2103 H   0  0  0  0  0  0  0  0  0  0  0  0
    4.8806   -1.9535   -1.5275 H   0  0  0  0  0  0  0  0  0  0  0  0
    4.9284   -1.3605    0.1417 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  1  3  1  0  0  0  0
  1  4  1  0  0  0  0
  1  5  1  0  0  0  0
  5  6  1  0  0  0  0
  5  8  1  0  0  0  0
  5  9  1  0  0  0  0
  6  7  1  0  0  0  0
  6 10  1  0  0  0  0
  6 11  1  0  0  0  0
  7 12  1  0  0  0  0
  7 13  1  0  0  0  0
  7 14  1  0  0  0  0
M  CHG  1   1   1
M  END
$$$$
```

poltype.ini:
```
structure=propylammonium.sdf
atmidx=501

use_gausoptonly=True

numproc=4
maxmem=20GB
maxdisk=100GB

printoutput=True
sleeptime=5
```

**Comment by walkerbdev** [comment]
I believe there is an issue with the way the latest tinker parses key files with large parameter type numbers. I get an error message that looks like
At line 1595 of file potential.f
Fortran runtime error: Index '404' of dimension 1 of array 'equiv' above upper bound of 14
This is currently posted on TinkerTools github. We can switch back to previous tinker in the mean time.

- Brandon

**Comment by mquevill** [comment]
It is fixed in the current `release` branch of Tinker. Thanks for the help!
