### ISSUE TITLE
Inconsistent or unspecified chg/mult

### ISSUE THREAD

**Issue by BelyaevaJuly** [pren/poltype#71]
Good afternoon, dear colleagues again, still have troubles with "+1 charged" ami parameterization. 
Now I have an issue at the step of geometry optimization (**Gaussian could not be used** because we have not got it).
An error itself:
!----------------------------------------------------------------------------------!
!                                                                                  !
!  I**nconsistent or unspecified chg/mult**: sys chg: None, frag chg: [0.0], sys mult: !
!     None, frag mult: [1]                                                         !
!                                                                                  !
!----------------------------------------------------------------------------------!

**All outputs are available here**:
https://drive.google.com/file/d/1kROw2AT21yRf1EMQNyJeOssRwMdxO3mT/view?usp=sharing

**Comment by walkerbdev** [comment]
Hey,

This has been fixed sometime within 1-2 weeks, I dont remember. Please do a git pull, and try again.

- Brandon
