### ISSUE TITLE
Conflicting flags with use_gausgeomoptonly

### ISSUE THREAD

**Issue by mquevill** [pren/poltype#74]
Setting `use_gausgeomoptonly` also sets the other `use_gaus`-type flags. However, there are two places where it sets different flags, but they seem to be conflicting. Why is this the case?

https://github.com/pren/poltype/blob/d80e40143542fef049ce143288616f05d28e0c7c/PoltypeModules/poltype.py#L1151-L1152

https://github.com/pren/poltype/blob/d80e40143542fef049ce143288616f05d28e0c7c/PoltypeModules/poltype.py#L1166-L1168

**Comment by walkerbdev** [comment]
Dont worry about it, this is intended to mean use gaussian for geometry
optimization and psi4 for torsion optimization. The behaviour works as
expected. I have not gotten around to adding docs as this is not really
important at the moment.

**Comment by walkerbdev** [comment]
I should specify, gaussian for the very first geometry optimization and
psi4 for torsion geometry optimization.
