### ISSUE TITLE
conda environment fails on parmed

### ISSUE THREAD

**Issue by blakemertz** [pren/poltype#79]
I've been attempting to set up an environment for poltype -- installed miniconda for Linux (running Debian10), have purged all my distribution-based python packages that were conflicting with the install, and added numpy to my environment.yml because I had too many other packages in Debian depending on numpy (I'm running python3.9 on my system). When I went to create the poltype environment, pip failed to build parmed from the start, throwing errors to build the wheel after cloning from git (see attached output).

This is my first time using conda, so I apologize if the issue is because  of conda instead of poltype, but thought this would be a good place to start from.
[conda-install-2-8-21.txt](https://github.com/pren/poltype/files/5951931/conda-install-2-8-21.txt)
 Thanks.

**Comment by walkerbdev** [comment]
Go ahead and try to use the .yaml file provided, see if that helps. If not,
I may end up removing parmed entirely, it doesnt provide 100% all of the
things we want.

**Comment by mquevill** [comment]
It looks like the most recent commit (https://github.com/ParmEd/ParmEd/commit/917343a9f4afc89965d0642ae10eb7550427e508) introduced some *major* changes as they removed Python 2 and did a lot of cleanup. I'm guessing this is the culprit, even though the main CI builds completed.

**Comment by blakemertz** [comment]
Thanks for the quick response. I commented out the calls to parmed in my yml and conda was able to successfully create the environment. Is it worth it to have a separate installation of parmed and just reference it to my PATH when I load the poltype environment? Just curious, as I'm only beginning to learn the ropes with poltype.

**Comment by mquevill** [comment]
You can edit the environment.yml file to get ParmEd from Conda-Forge instead of directly from GitHub. See changes here: https://github.com/pren/poltype/pull/80/commits/8a9199698e2593fe0741e5c4b20664adad2a27e3
You can then either update the Conda environment or delete it and create a new one with the new environment file.

**Comment by walkerbdev** [comment]
I will remove it from official yaml file later today also. It was intended
for unit testing but their parser has issues under special circumstances.
