### ISSUE TITLE
OpenBabel 3.0 compatibility

### ISSUE THREAD

**Issue by mquevill** [pren/poltype#8]
When installing OpenBabel with `conda install -c openbabel openbabel`, version 3.0.0 is installed. However, there are some breaking changes in the API that do not allow poltype to run. https://open-babel.readthedocs.io/en/latest/UseTheLibrary/migration.html#handling-of-elements-and-related-information

Namely, the Element table no longer exists. The information that would have been acquired from `etab = openbabel.OBElementTable()` is now available _directly_ from `openbabel`.

Take an example from `optimization.py`:
```diff
-    etab = openbabel.OBElementTable()
     for atm in iteratombab:
-        tmpfh.write('%2s %11.6f %11.6f %11.6f\n' % (etab.GetSymbol(atm.GetAtomicNum()), atm.x(), atm.y(), atm.z()))
+        tmpfh.write('%2s %11.6f %11.6f %11.6f\n' % (openbabel.GetSymbol(atm.GetAtomicNum()), atm.x(), atm.y(), atm.z()))
```

There's also an issue with the format of the import statements. OpenBabel now requires `from openbabel import openbabel` instead of `import openbabel`, which is handled by #6.

If you want to only support OpenBabel 3.0.0, the changes are very straightforward and simple. However, if you would like to support 2.x and 3.0 together, it then becomes a more complicated situation.

**Comment by pren** [comment]
Thanks for bring this to attention. Our conda has been installing openbabel 2.4 and we have not tested 3.0. Brandon will look into this.
Which OS are you running this on and what version?

**Comment by pren** [comment]
And we always get openbabel 2.x using "conda install -c openbabel openbabel." Did you by any chance used conda-forge channel? "conda install -c conda-forge openbabel"

**Comment by walkerbdev** [comment]
Hi,
Thank you for pointing this out. I have modified the README_INSTALL file to specify version for openbabel to be 2.4.0. Please see if this works. The unittesting module does have some bugs as well as the fragmenter and modifiedresidue libs currently.

**Comment by mquevill** [comment]
Installing with `conda install -c openbabel openbabel` is **deprecated**, so it automatically redirects to using conda-forge.
```
$ conda install -c openbabel openbabel
The following NEW packages will be INSTALLED:
  openbabel          conda-forge/linux-64::openbabel-3.0.0-py38hdef5451_1
```

Furthermore, 2.4.0 does not exist on even the openbabel channel. 2.4.1 is the only version available through that channel. I would recommend changing the installation line to:
```
conda install -c conda-forge openbabel=2.4.1
```

However, in my conda installation, it was using Python 3.8, which is not supported by OpenBabel 2.4.1. Perhaps this is why is switched to conda-forge and installed 3.0.0. I downgraded to Python 3.7 and installed OpenBabel 2.4.1.

**Comment by leucinw** [comment]
@mquevill It should be clear that it is python 3.8 that guides you to conda-forge. I have python 3.7.4 with my anaconda. When I run ```condo search -c conda-forge``` I can see there are 2.4.1 and 3.0.0 there. So choose the 2.4.1 one.
```
$ conda search -c conda-forge openbabel
Loading channels: done
# Name                       Version           Build  Channel
openbabel                      2.4.1  py27hc189817_0  conda-forge
openbabel                      2.4.1  py27hc189817_1  conda-forge
openbabel                      2.4.1  py36hc189817_0  conda-forge
openbabel                      2.4.1  py36hc189817_1  conda-forge
openbabel                      2.4.1  py37hc189817_0  conda-forge
openbabel                      2.4.1  py37hc189817_1  conda-forge
openbabel                      3.0.0  py27h1360c68_0  conda-forge
openbabel                      3.0.0  py27hdef5451_1  conda-forge
openbabel                      3.0.0  py36h1360c68_0  conda-forge
openbabel                      3.0.0  py36hdef5451_1  conda-forge
openbabel                      3.0.0  py37h1360c68_0  conda-forge
openbabel                      3.0.0  py37hdef5451_1  conda-forge
openbabel                      3.0.0  py38hdef5451_1  conda-forge
```
If I search using openbabel channel, I can see there is only openbabel 2.4.1
```
$ conda search -c openbabel openbabel
Loading channels: done
# Name                       Version           Build  Channel
openbabel                      2.4.1          py27_0  openbabel
openbabel                      2.4.1          py27_1  openbabel
openbabel                      2.4.1          py27_2  openbabel
openbabel                      2.4.1          py27_3  openbabel
openbabel                      2.4.1          py27_5  openbabel
openbabel                      2.4.1          py27_6  openbabel
openbabel                      2.4.1          py34_0  openbabel
openbabel                      2.4.1          py34_1  openbabel
openbabel                      2.4.1          py34_2  openbabel
openbabel                      2.4.1          py34_3  openbabel
openbabel                      2.4.1          py34_5  openbabel
openbabel                      2.4.1          py35_0  openbabel
openbabel                      2.4.1          py35_1  openbabel
openbabel                      2.4.1          py35_2  openbabel
openbabel                      2.4.1          py35_3  openbabel
openbabel                      2.4.1          py35_5  openbabel
openbabel                      2.4.1          py35_6  openbabel
openbabel                      2.4.1          py36_2  openbabel
openbabel                      2.4.1          py36_3  openbabel
openbabel                      2.4.1          py36_5  openbabel
openbabel                      2.4.1          py36_6  openbabel
openbabel                      2.4.1          py37_5  openbabel
openbabel                      2.4.1          py37_6  openbabel
```
