### ISSUE TITLE
KeyError in databaseparser

### ISSUE THREAD

**Issue by mquevill** [pren/poltype#85]
When trying to run the ModifiedAminoAcid example, there's a KeyError in some of the indices. I had this issue with both Gaussian and with only Psi4.

```
  File "/path/to/poltype/PoltypeModules/databaseparser.py", line 1137, in <listcomp>
    smartindices=[moleculeindextosmartsindex[i] for i in atomindices]
KeyError: 13
```

[I commented out lines in poltype.ini for `bashrcpath`, `externalapi`, and `amoebabioprmpath`, since these are specific to certain users/systems.]

**Comment by walkerbdev** [comment]
yes, the modified residues lib is currently broken for many months, however, this appears to be unrelated error.
