### ISSUE TITLE
Cube files take up a lot of space

### ISSUE THREAD

**Issue by mquevill** [pren/poltype#88]
When generating the .cube files, there are many files that get created, which can add up in file space. Perhaps this should be an option that the user needs to specify in the input file so that it doesn't create files that take up a huge amount of space. Each file itself isn't that large, but when thousands of files are being generated, it can definitely add up. Running a molecule with ~25 atoms generates ~3000 files that add up to 30+ GB. If someone doesn't need to use these file, they shouldn't need to be generated.

**Comment by mquevill** [comment]
Whoops, I see you had a very recent commit reducing the number of output files.

**Comment by walkerbdev** [comment]
:)
